# Generated by Django 4.2.11 on 2024-06-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Constituency Name')),
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('region', models.CharField(choices=[('NE', 'North East'), ('NW', 'North West'), ('Y', 'Yorkshire and the Humber'), ('WM', 'West Midlands'), ('EM', 'East Midlands'), ('SW', 'South West'), ('SE', 'South East'), ('L', 'London'), ('E', 'East of England'), ('S', 'Scotland'), ('W', 'Wales')], max_length=2, verbose_name='Region')),
                ('winner2019', models.CharField(choices=[('Con', 'Conservative and Unionist Party'), ('Lab', 'Labour Party'), ('LD', 'Liberal Democrats'), ('SNP', 'Scottish National Party'), ('Grn', 'Green Party'), ('Ref', 'Reform UK'), ('PC', 'Plaid Cymru'), ('WPB', 'Workers Party of Britain'), ('SDP', 'Social Democratic Party'), ('UKIP', 'UK Independence Party'), ('Alba', 'Alba Party'), ('Ind', 'Independent'), ('Oth', 'Other')], max_length=4, verbose_name='2019 Winner')),
                ('age_under_25', models.DecimalField(decimal_places=1, max_digits=4)),
                ('age_25_34', models.DecimalField(decimal_places=1, max_digits=4)),
                ('age_35_49', models.DecimalField(decimal_places=1, max_digits=4)),
                ('age_50_64', models.DecimalField(decimal_places=1, max_digits=4)),
                ('age_over_65', models.DecimalField(decimal_places=1, max_digits=4)),
                ('immigrant', models.DecimalField(decimal_places=1, max_digits=4)),
                ('white', models.DecimalField(decimal_places=1, max_digits=4)),
                ('religion_christian', models.DecimalField(decimal_places=1, max_digits=4)),
                ('religion_islam', models.DecimalField(decimal_places=1, max_digits=4)),
                ('religion_hindu', models.DecimalField(decimal_places=1, max_digits=4)),
                ('religion_other', models.DecimalField(decimal_places=1, max_digits=4)),
                ('base_con', models.DecimalField(blank=True, decimal_places=3, max_digits=4)),
                ('base_lab', models.DecimalField(blank=True, decimal_places=3, max_digits=4)),
                ('base_ld', models.DecimalField(blank=True, decimal_places=3, max_digits=4)),
                ('base_ref', models.DecimalField(blank=True, decimal_places=3, max_digits=4)),
                ('base_grn', models.DecimalField(blank=True, decimal_places=3, max_digits=4)),
                ('base_snp', models.DecimalField(blank=True, decimal_places=3, max_digits=4)),
                ('base_pc', models.DecimalField(blank=True, decimal_places=3, max_digits=4)),
                ('base_min', models.DecimalField(blank=True, decimal_places=3, max_digits=4)),
            ],
            options={
                'verbose_name': 'constituency',
                'verbose_name_plural': 'constituencies',
                'ordering': ['name'],
            },
        ),
    ]
