# Generated by Django 4.2.11 on 2024-06-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Constituency Name')),
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('region', models.CharField(choices=[('NE', 'North East'), ('NW', 'North West'), ('Y', 'Yorkshire and the Humber'), ('WM', 'West Midlands'), ('EM', 'East Midlands'), ('SW', 'South West'), ('SE', 'South East'), ('L', 'London'), ('E', 'East of England'), ('S', 'Scotland'), ('W', 'Wales')], max_length=2, verbose_name='Region')),
            ],
            options={
                'verbose_name': 'constituency',
                'verbose_name_plural': 'constituencies',
                'ordering': ['name'],
            },
        ),
    ]
