# Generated by Django 4.2.11 on 2024-06-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='winner2019',
            field=models.CharField(choices=[('Con', 'Conservative and Unionist Party'), ('Lab', 'Labour Party'), ('LD', 'Liberal Democrats'), ('SNP', 'Scottish National Party'), ('Grn', 'Green Party'), ('Ref', 'Reform UK'), ('PC', 'Plaid Cymru'), ('WPB', 'Workers Party of Britain'), ('SDP', 'Social Democratic Party'), ('UKIP', 'UK Independence Party'), ('Alba', 'Alba Party'), ('Ind', 'Independent'), ('Oth', 'Other')], default='Oth', max_length=4, verbose_name='2019 Winner'),
            preserve_default=False,
        ),
    ]
