# Generated by Django 4.2.11 on 2024-06-27 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_constituency_base_con_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed', models.BooleanField(default=False)),
                ('winner', models.CharField(choices=[('Con', 'Conservative and Unionist Party'), ('Lab', 'Labour Party'), ('LD', 'Liberal Democrats'), ('SNP', 'Scottish National Party'), ('Grn', 'Green Party'), ('Ref', 'Reform UK'), ('PC', 'Plaid Cymru'), ('WPB', 'Workers Party of Britain'), ('SDP', 'Social Democratic Party'), ('UKIP', 'UK Independence Party'), ('Alba', 'Alba Party'), ('Ind', 'Independent'), ('Oth', 'Other')], max_length=4)),
                ('con', models.FloatField(blank=True, null=True)),
                ('lab', models.FloatField(blank=True, null=True)),
                ('ld', models.FloatField(blank=True, null=True)),
                ('ref', models.FloatField(blank=True, null=True)),
                ('grn', models.FloatField(blank=True, null=True)),
                ('snp', models.FloatField(blank=True, null=True)),
                ('pc', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='basic_projection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='basic_projections', to='model.projection'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='detailed_projection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detailed_projections', to='model.projection'),
        ),
    ]
