# Generated by Django 4.2.11 on 2024-06-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_totalseats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalseats',
            name='declared',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='totalseats',
            name='projected',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
