# Generated by Django 4.2.11 on 2024-06-29 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_result_total_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='basic_projection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basic_projections', to='model.projection'),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='detailed_projection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailed_projections', to='model.projection'),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.result'),
        ),
    ]
